# Generated by Django 3.0.8 on 2020-07-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VIN', models.CharField(max_length=17)),
                ('MAC', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=13)),
            ],
        ),
    ]
