# Generated by Django 3.0.8 on 2020-09-25 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VIN', models.CharField(max_length=20, unique=True, verbose_name='차대번호(17자리)')),
                ('MAC', models.CharField(max_length=20, unique=True, verbose_name='MAC주소(12자리)')),
                ('name', models.CharField(max_length=20, verbose_name='운전자 이름')),
                ('tel', models.CharField(max_length=20, unique=True, verbose_name='연락처(-포함)')),
            ],
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myfile', models.FileField(upload_to='', verbose_name='파일 업로드')),
            ],
        ),
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mycar_date', models.CharField(max_length=37, unique=True, verbose_name='차대번호(17자리)_사고발생시간')),
                ('date', models.CharField(max_length=20, verbose_name='사고발생시간')),
                ('noregicar', models.CharField(blank=True, max_length=10000, verbose_name='기기등록X차량 mac주소 모음')),
                ('carcount', models.IntegerField(default=0, verbose_name='차량수')),
                ('mycar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mycar', to='myapp.Device')),
                ('othercars', models.ManyToManyField(blank=True, related_name='othercars', to='myapp.Device')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('nickname', models.CharField(max_length=30, verbose_name='user name')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자들',
            },
        ),
    ]
