# Generated by Django 3.0.8 on 2020-07-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='MAC',
            field=models.CharField(max_length=12, verbose_name='MAC주소(12자리)'),
        ),
        migrations.AlterField(
            model_name='register',
            name='VIN',
            field=models.CharField(max_length=17, verbose_name='차대번호(17자리)'),
        ),
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(max_length=20, verbose_name='운전자 이름'),
        ),
        migrations.AlterField(
            model_name='register',
            name='tel',
            field=models.CharField(max_length=13, verbose_name='연락처'),
        ),
    ]
