# Generated by Django 3.0.8 on 2020-07-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='carcount',
            field=models.IntegerField(default=0, verbose_name='차량수'),
        ),
    ]
