# Generated by Django 3.0.8 on 2020-07-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200729_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='noregicar',
            field=models.CharField(blank=True, max_length=10000, verbose_name='등록안된차량 mac주소'),
        ),
    ]
