# Generated by Django 3.0.8 on 2020-07-09 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_userfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfile',
            old_name='file',
            new_name='myfile',
        ),
    ]
