# Generated by Django 3.0.8 on 2020-07-09 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200709_1613'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFile',
            new_name='FileUpload',
        ),
    ]
